update README.md
Hexlet/hexlet-sicp pull request #1021
Opened 2021-08-17 22:20 UTC by AABur

Slightly updated Russian README
Frankly, for an article on the Hexlet blog. Made some cosmetic edits at the same time.

2021-08-18 09:04 UTC, fey commented on README.md
> +## Участие в разарботке
Опечатка

2021-08-18 09:04 UTC, fey commented on README.md
> +## Предварительные требовани
опечатка

2021-08-18 09:06 UTC, fey commented on README.md
> +2. Указать параметры подключения к БД в файле `.env`
Имена файликов оформляем в астериксы (из внутр. стайлгайда хекслета), бектики для кода

2021-08-18 09:06 UTC, fey commented on README.md
> +```sh
в Markdown нужен отступ в элементе списка, если он состоит из нескольких абзацев

2021-08-18 09:07 UTC, fey commented on README.md
> +1. Подготовить файл `.env`
.env - можно убрать бектики и обернуть в *

2021-08-18 09:08 UTC, fey requested changes
Оставил пару комментов, в остальном вроде норм :+1:

2021-08-18 09:13 UTC, fey commented
@AABur https://hexlet.notion.site/57fd9c773cc04c6da2cc105646eab129

2021-08-18 09:57 UTC, fey commented
В этом ПР можно поправить замечания текущие, а в след - по стайлгайду поправить весь ридми :)

2021-08-18 18:57 UTC, fey commented
Нужно сделать ребейз

2021-08-22 23:24 UTC, AABur commented
внёс правки в соответствии стайлгайду

2021-08-23 07:22 UTC, fey commented
@AABur 
Смотри, у тебя получился мердж с мастером
Merge branch 'readme-update' of github.com:AABur/hexlet-sicp into rea…

Как надо было сделать - сделать ребейз на мастер, это делается примерно так `git pull --rebase upstream master`.
Удали. пожалуйста, коммит из мерджа, чтобы были только твои коммиты и сделай ребейз, если нужна помощь, То отпишись в слаке

2021-08-31 09:57 UTC, AABur commented
Не получилось у меня корректно с мердж-реквестом разобраться. Сделаю новый PR чистый

2021-08-31 09:57 UTC, closed without merging