[#653] issue rddeveloper
Hexlet/hexlet-sicp pull request #1274
Opened 2022-03-21 18:16 UTC by rddeveloper2019

[#653]
Deployed on Heroku from new created branch  
https://rdweb-hexlet-sicp-app.herokuapp.com/ru

2022-03-22 08:43 UTC, fey commented on resources/views/layouts/_footer.blade.php
> +                    <li><a target="_blank" href="https://guides.hexlet.io/">{{ __('layout.footer.os_projects.guides') }}</a></li>
Тепреь это можно убрать.

2022-03-22 08:44 UTC, fey commented on resources/views/layouts/bootstrap5/app.blade.php
> +    </main>
@amshkv можешь посмотреть, пожалуйста?

2022-03-22 08:58 UTC, amshkv commented on resources/views/layouts/bootstrap5/app.blade.php
> +    </main>
кажется что `my-4` дублирует `.mb-4` на ребенке
еще не понимаю для чего отрицательный отступ `.mt-n2`? он вообще работает? в 5м бутстрапе его надо отдельно включать

2022-03-22 11:04 UTC, rddeveloper2019 commented
Убрал лишнюю ссылку.
В этих классах "container-xl mt-n2 mb-4" я ничего не исправлял.

2022-03-22 14:35 UTC, rddeveloper2019 commented on resources/views/layouts/bootstrap5/app.blade.php
> +        <main class='my-4'>
Смотрел на версию bootstrap 4. Применил тоже самое. Особо не вникал, если честно.

2022-03-22 14:44 UTC, fey commented on resources/views/layouts/bootstrap5/app.blade.php
> +        <main class='my-4'>
@rddeveloper2019 можешь завести ишшус? Чтобы потом мы поправили

2022-03-22 15:09 UTC, fey commented on resources/views/layouts/bootstrap5/app.blade.php
> +        <main class='my-4'>
Давай здесь вернем старую верстку (в бс5 шаблоне она в принципе неплохая), потом её отдельным ПР изменим.
Создать ишшус - просто ишшус в котором условно "поправить замечания из такого-то пулл реквеста" и ссылку на ПР.
Просто щас не могу принять ПР потому что изменения не очень понятные. На демонстрации их не видно, например
https://rdweb-hexlet-sicp-app.herokuapp.com/ru/password/reset

2022-03-22 15:13 UTC, rddeveloper2019 commented on resources/views/layouts/bootstrap5/app.blade.php
> +        <main class='my-4'>
Ок

2022-03-24 14:07 UTC, fey requested changes

2022-03-24 14:07 UTC, fey commented on resources/views/layouts/bootstrap5/app.blade.php
> +        <main class='my-4'>
Здесь изменения не нужны. 
Как уберешь - можем принять пр =)

2022-03-27 08:13 UTC, rddeveloper2019 commented
Вроде навёл порядок чуть чуть

2022-03-27 08:15 UTC, rddeveloper2019 commented
![old](https://user-images.githubusercontent.com/63258916/160273009-43888607-6928-4f11-a5f8-f757c8881159.png)
![new](https://user-images.githubusercontent.com/63258916/160273011-46b9b067-6f2c-4e97-9462-2bd9181eeb14.png)
https://rdweb-hexlet-sicp-app.herokuapp.com/ru/password/reset

2022-03-27 08:28 UTC, merged