1346 user comments
Hexlet/hexlet-sicp pull request #1375
Opened 2022-10-11 12:14 UTC by vasilysmolin

Page with all users comments and link to this page

2022-10-14 05:30 UTC, ashikov commented
Про PR помню. Приболел. В ближайшее время гляну.

2022-10-14 09:57 UTC, ashikov requested changes

2022-10-14 09:57 UTC, ashikov commented on resources/lang/ru/comment.php
> +        'whom' => 'Кому',
Думаю тут лучше написать не "Кому", а "Место комментария" или можно ещё подумать над вариантами, чтобы было понятно

2022-10-14 09:57 UTC, ashikov commented on resources/lang/en/comment.php
> +        'title' => 'My comment',
Так как переход на страницу со всеми комментариями происходит со страницы рейтинга, то имеет смысл сделать тайтл вида: "Комментарии пользователя <username>", а не "Мои комментарии".

2022-10-14 09:57 UTC, ashikov commented on resources/views/user/comment/index.blade.php
> +                            <td>{{ $comment->content }}</td>
![Screenshot from 2022-10-14 16-49-11](https://user-images.githubusercontent.com/676554/195817788-cbf473f8-6d2d-46fe-9aba-db3af326a461.png)
Дата не помещается в поле

2022-10-14 09:57 UTC, ashikov commented on resources/lang/ru/comment.php
> +        'whom' => 'Кому',
Ключ конечно тоже стоит поменять и поправить везде

2022-10-14 09:57 UTC, ashikov commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
Таб с обсуждениями в упражнении не открывается автоматом при переходе по ссылке

2022-10-18 13:25 UTC, vasilysmolin commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
/exercises/73#exercise-discussion - в роуте добавлял hash, надо доработать сами табы в упражненении, чтобы в зависимости от hash в урле становился активный нужный таб?

Сейчас всегда первый таб по умолчанию открывается.

2022-10-18 13:47 UTC, ashikov commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
По идее да. Если мы можем ссылаться на таб, то логично, чтобы он открывался при переходе по этой ссылке. Можно это отдельным PR-ом тогда. В issue оформляю или так пильнешь?)

2022-10-18 13:51 UTC, vasilysmolin commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
Здесь тогда доработаю этот момент

2022-10-19 06:18 UTC, vasilysmolin commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
![image](https://user-images.githubusercontent.com/28043582/196610490-2de960ca-4fe1-4c19-a3b4-6ed34ecb36f9.png)

В целом был код который отвечает за активные табы custom.js , но не работает функция tab почему-то. пробовал разные варианты её подрубить, но пока не получилось
```
  if (url.indexOf('#') > 0) {
    const activeTab = url.substring(url.indexOf('#') + 1);
    $(`.nav[role="tablist"] a[href="#${activeTab}"]`).tab('show');
  }

```
Вот такое решение могу предложить, руками вешать на табы нужные классы.

```
if (url.indexOf('#') > 0) {
    const activeTab = url.substring(url.indexOf('#') + 1);
    const elementActiveTab = $(`#${activeTab}`);
    if(elementActiveTab.length > 0) {
      $(`.nav[role="tablist"] > li > a`).removeClass('active');
      $(`#pills-tabContent > div[role="tabpanel"]`).removeClass('active').removeClass('show');
      $(`.nav[role="tablist"] a[href="#${activeTab}"]`).addClass('active');
      elementActiveTab.addClass('active').addClass('show');
    }
  }
```

Подойдет? или копать почему tab не подрубается?

2022-10-19 06:33 UTC, ashikov commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
Думаю лучше копнуть. Ну и если долго, то в отдельный issue вынести этот баг.

2022-10-19 07:20 UTC, vasilysmolin commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
Давай тогда в отдельный issue вынесем. Всё остальное поправил вроде.

2022-10-19 07:52 UTC, ashikov commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
Окей. Я чуть позже сделаю и смержу.

2022-10-19 13:05 UTC, ashikov commented on resources/views/user/comment/index.blade.php
> +                                    href="{{ route('exercises.show', [$comment->commentable,'#exercise-discussion']) }}"
Тык -> #1377

2022-10-19 13:33 UTC, merged