[#220] Статистика на главной странице
Hexlet/hexlet-sicp pull request #1405
Opened 2022-11-21 12:06 UTC by AslanAV

- добавлена статистика в контроллер HomeController.php
 - на главной странице залогиненного пользователя выводится статистика по все время/за месяц/за неделю

2022-11-21 19:55 UTC, AslanAV commented
https://hexlet-sicp-aslan-av.herokuapp.com/
новый дизайн лендинга
для входа на сайт (старый дизайн) надо 2 раза нажать dev-login

2022-11-24 18:24 UTC, fey commented on app/Http/Controllers/HomeController.php
> +        $query = $_GET['filter'] ?? '';
мы не обращаемся к глобальному массиву с параметрами Есть механизмы фреймворка
Плюс здесь уже эти параметры должны как минимум передаваться через метод

2022-11-24 18:25 UTC, fey commented on app/Http/Controllers/HomeController.php
> +        $readChapters = new ReadChapter();
readChapters - множественное число, а по факту это одна моделька

2022-11-24 18:26 UTC, fey commented on app/Http/Controllers/HomeController.php
> +            $countCompletedExercise = $completedExercise->all()->count();
для выполнения запросов билдера можно сразу вызывать через статическй метод, без создания инстанса. Плюс есть метод SQL count чтобы не вытаскиывать данные, а сразу их посчитать.

2022-11-24 18:26 UTC, fey commented on app/Http/Controllers/HomeController.php
> +            $subPeriod = 'sub' . $query;
интерполяция вместо конкатенации

2022-11-24 18:29 UTC, fey requested changes

2022-11-24 18:29 UTC, fey commented on app/Http/Controllers/HomeController.php
> +            'countPoints' => $countReadChapters + $countCompletedExercise * 3,
какая-то магия

2022-11-24 18:29 UTC, fey commented on resources/views/home/index.blade.php
> +            Интерактивная версия книги SICP
переводы

2022-11-24 18:29 UTC, fey commented on resources/views/home/index.blade.php
> +{{--            @endif--}}
комментарии

2022-11-24 18:29 UTC, fey commented on resources/views/home/index.blade.php
> +                            {{ request()->getQueryString() === "filter=month" ? 'active' : '' }}
кажется это не то место, где нужно обращаться к квер параметрам. Стоит их передавать из контроллера

2022-11-24 18:29 UTC, fey commented on resources/views/home/index.blade.php
> +                        href="/?filter=week"
Это хардкод. У ларавеля есть хелперы для роутов и параметров

2022-11-24 18:29 UTC, fey commented on resources/views/home/oldLanding.blade.php
> +@extends('layouts..app')
у нас есть гит, не нужно бекапить старые файлы

2022-11-27 08:14 UTC, closed without merging