remove solution slice and keep the solution state local within the co…
Hexlet/hexlet-sicp pull request #1528
Opened 2023-03-19 14:18 UTC by antonDedyaev

Fixes #1526

Simplified solution display logic by implementing local state in the TeacherSolution component.

2023-03-24 15:06 UTC, dzencot requested changes

2023-03-24 15:06 UTC, dzencot commented on resources/js/components/TeacherSolution.jsx
> +const startTime = Date.now();
Предлагаю это в `useEffect` и хранить через `useState`. Иначе в теории это будет срабатывать задолго до рендера компонента.

2023-03-24 16:02 UTC, antonDedyaev commented on resources/js/components/TeacherSolution.jsx
> +const startTime = Date.now();
Да, мне тоже этот таймер покоя не давал - про useEffect сразу не подумал, сделаю!

2023-03-31 06:43 UTC, ssssank commented
@antonDedyaev получается сделать?

2023-03-31 10:37 UTC, antonDedyaev commented
> @antonDedyaev получается сделать? 

Да, я сделаю.
Просто на работе запарка. На выходных планировал.

2023-04-11 09:07 UTC, merged