#628 progress default page changed
Hexlet/hexlet-sicp pull request #1590
Opened 2023-09-01 19:32 UTC by ddm14159

#628 По умолчанию открываем первый раздел, в котором есть непрочитанные главы. Если прочитано все, то показываем начало

2023-09-04 10:44 UTC, sgmdlt commented
@fey

2023-09-06 08:09 UTC, fey requested changes
Я бы предложил переписать код. Смотрите, у нас есть сервисы https://github.com/Hexlet/hexlet-sicp/tree/main/app/Services
 и там можно создать chapterService и добавить всю логику по работе с главами. 
 Т.е. если пользователь отмечает прочитанной главы - то проверяем, все ли они относятся к mainChapter. 
 Соответственно, нам бы оставалось просто брать главные главы книги и главные главы пользователя, и строить запрос, чтобы получать первую главу, которая еще не отмечена прочитанной.

2023-09-06 08:09 UTC, fey commented on app/Http/Controllers/MyController.php
> +        $mainChapters = $chapters->where('parent_id', null)->sortBy('id');
давайте добавить scope для получения главных глав. 
По сортировке-  надежнее использовать сортировку по path. Тогда это будет по смыслу ближе к нашей предметной области. ведь у наших глав в книге нет айдишников, есть ее номера.

2023-09-11 09:43 UTC, ola-9 commented
@ddm14159 скажите, пожалуйста, нужна ли какая-нибудь помощь, как продвигается работа?

2025-06-02 15:46 UTC, closed without merging