fixed title for page show chapter, exercise, solution
Hexlet/hexlet-sicp pull request #1619
Opened 2024-03-28 03:12 UTC by Kolalexx

## Pull request details

## Issues fixed

## Link to demo

[1]: https://github.com/{owner}/{repo}/pulls
[2]: https://github.com/{owner}/{repo}/blob/master/.github/CONTRIBUTING.md#code-style

2024-03-28 09:41 UTC, fey commented
@Kolalexx Добрый день, задеплойте демку на render

2024-03-28 09:42 UTC, fey commented on app/Models/Chapter.php
> +    }
хелпер не стоит использовать внутри модели. Хелпер это что-то, что находится вне модели/предметной области. Обычно это хелперы для UI/HTML, чтобы не писать несколько раз одно и то же. Более правильно модель передавать в хелпер

2024-03-28 09:46 UTC, fey commented on resources/views/exercise/show.blade.php
> +  {{ __('exercise.exercise') }} {{ getTitleContent($exercise->getFullTitle()) }}
суть `getTitleContent` в том, что он занимается оформлением окончательного тайтла. Посмотрите в код, увидите, что там в хедер добавляется строка с назвнаием проекта. Поэтому равильный путь будет передать все нужные строки в функцию getTitleContent. 
По идее можно создать новую метку для переводов и туда передавать нужную переменную. https://laravel.com/docs/11.x/localization#replacing-parameters-in-translation-strings

2024-03-31 04:50 UTC, Kolalexx commented
@fey Добрый день. Ссылка на демку на render - https://hexlet-sicp-k2jq.onrender.com

2024-04-01 09:28 UTC, fey requested changes
Использование презентера - ок, можно это дальше использовать, но только для формирования полного имени сущности, например "упражнение 1.3 lalala", но в getTitle должна передаваться строка, а не модель. Ну и стоит убрать взаимосвязанный вызов презентер -> модель -> презнтер

2024-04-01 09:28 UTC, fey commented on app/Helpers/TemplateHelper.php
> +    public static function getTitleContent(object $model): string
@Kolalexx тут на самом деле не нужно изменять метод. Во первых неверно передавтаь object - ведь тогда вообще любой обьект может быть передан, но у него может не быть метода. 
Во вторых - мы же не модель сюда передаем. Мы передаем уникальную строку, это может быть как название главы, название упражнения, имя пользователя, просто название страницы. 
Суть getTitleContent только в том, чтобы взять этот уникальный хедер, который должен быть на странице и добавить к нему суффикс. 

Т.е. метод то не нужно изменять. Мы его используем как есть и передаем внутрь строку.

2024-04-01 09:28 UTC, fey commented on app/Models/Solution.php
> +    }
вообще какая-то наркомания получается. Смотри, в exercise сейчас этот метод делает вызов презентера `return $this->present()->fullTitle;`, а тут мы наоборот вызываем метод в модели, чтобы она внутри вызвалась внутри презентера.

2024-04-01 09:28 UTC, fey commented on app/Models/Solution.php
> +    }
метод называется "получить имя модели", а возвращается `Решение для упражнения` по сути тайтл, который относится к слою view

2024-04-02 03:05 UTC, Kolalexx commented
@fey вроде учел все замечания, прошу посмотреть

2024-04-02 16:41 UTC, fey requested changes

2024-04-02 16:41 UTC, fey commented on app/Helpers/TemplateHelper.php
> +    public static function getTitleContent(string $header, string $title): string
Смотри, здесь ты добавил `$title` - но по сути это дубль `$header`. Внутрь функции getTitleContent попадает одна строк - хедер, который должен вывестись. Просто к этому хедеру сборку прикручивается название проекта. Т.е. строку хедера надо снаружи передать в функцию, без изменения сигнатуры `getTitleContent`.

2024-04-02 16:41 UTC, fey commented on resources/views/solution/show.blade.php
> +  {{ getTitleContent($currentExercise->getFullTitle(), __('solution.solution_for_title')) }}
Это делается по-другому. в строку локали можно передать парамтер (для этого надо обновить строку локали), чтобы передать внутрь название упражнения

2024-04-02 16:41 UTC, fey commented on resources/views/solution/show.blade.php
> +  {{ getTitleContent($currentExercise->getFullTitle(), __('solution.solution_for_title')) }}
```suggestion
  {{ getTitleContent(__('solution.solution_for_title', ['exercise' => $currentExercise->getFullTitle()])) }}
```

2024-04-02 16:41 UTC, fey commented on resources/lang/ru/solution.php
> +    'solution_for_title' => 'Решение для упражнения',
```suggestion
    'solution_for_title' => 'Решение для упражнения :exercise',
```

2024-04-02 16:41 UTC, fey commented on resources/lang/ru/solution.php
> +    'solution_for_title' => 'Решение для упражнения',
Плюсом, когда добавляешь тексты для локали, нужно добавить для других локалей тоже (для англ)

2024-04-03 03:09 UTC, Kolalexx commented
@fey спасибо за помощь и терпение, надеюсь это финальная версия

2024-04-03 09:20 UTC, fey commented
@Kolalexx сейчас в двух файлах локалей конфликты, скорее всего в основной ветке дбавился код, поэтому конфликт. Попробуй сделать ребейз и стащить изменения из мейна. получится сделать самостоятельно?

2024-04-03 09:24 UTC, Kolalexx commented
@fey да завтра с утра сделаю

2024-04-04 02:12 UTC, closed without merging