Add pluralization in activity log
Hexlet/hexlet-sicp pull request #542
Opened 2020-09-10 15:41 UTC by Malcom1986

![activity_3](https://user-images.githubusercontent.com/46455978/92756037-1a96f980-f395-11ea-962d-da63c65a2477.jpeg)

![activity_4](https://user-images.githubusercontent.com/46455978/92756149-37cbc800-f395-11ea-90ed-be7676bd63bf.jpeg)

2020-09-10 16:16 UTC, fey requested changes

2020-09-10 16:16 UTC, fey commented on app/Helpers/ActivityLogHelper.php
> +    function getLogItemDescription(Activity $logItem, int $itemsCount = 1): string
Вроде в активити записывается колво уже

2020-09-10 16:16 UTC, fey commented on resources/lang/ru/activitylog.php
> +    'action_added' => 'Добавил главу:|Добавил главы:|Добавил глав:',
добавил глав: 6 не очень читается

2020-09-10 16:21 UTC, fey commented on resources/views/log/index.blade.php
> +                                        {{ getLogItemDescription($logItem, $logItem->getExtraProperty('count')) }} {{ $logItem->getExtraProperty('count') }}
и мне кажется, что лучше скрывать внутри то, как строится строка описания, Как видишь у тебя тут в 3 местах исправления пошли. Получается, что формат описания задается и снаружи и в файле ресурсов

2020-09-11 05:50 UTC, Malcom1986 commented on resources/lang/ru/activitylog.php
> +    'action_added' => 'Добавил главу:|Добавил главы:|Добавил глав:',
Можно попробовать сделать "добавил 6 глав"

2020-09-11 05:57 UTC, Malcom1986 commented on resources/views/log/index.blade.php
> +                                        {{ getLogItemDescription($logItem, $logItem->getExtraProperty('count')) }} {{ $logItem->getExtraProperty('count') }}
Т.е. всю логику построения строки описания лучше убрать в хэлпер getLogItemDescription?

2020-09-11 07:09 UTC, fey commented on resources/views/log/index.blade.php
> +                                        {{ getLogItemDescription($logItem, $logItem->getExtraProperty('count')) }} {{ $logItem->getExtraProperty('count') }}
Да, иначе размазано получается.
Чтобы изменить формат описания тебе нужно это делать во вьюхе зачем-то, а не в специальной функции созданной для этого.

2020-09-11 07:10 UTC, fey commented on resources/views/log/index.blade.php
> +                                        {{ getLogItemDescription($logItem, $logItem->getExtraProperty('count')) }} {{ $logItem->getExtraProperty('count') }}
Еще стоит учитывать, что можно пробрасывать значения в функцию перевода, поэтому можно не конкатенировать вручную строку.

2020-09-11 14:01 UTC, Malcom1986 commented
![activity_1](https://user-images.githubusercontent.com/46455978/92934655-6ce92080-f450-11ea-993f-1cec016fa1e2.jpeg)


![activity_2](https://user-images.githubusercontent.com/46455978/92934660-6d81b700-f450-11ea-9bbf-4060de3defb7.jpeg)

2020-09-11 14:04 UTC, merged