[#704] add filter by authors and exercises
Hexlet/hexlet-sicp pull request #728
Opened 2021-03-17 20:10 UTC by vladimirkuvanovv

Добавлен фильтр по авторам и упражнениям

2021-03-17 20:11 UTC, vladimirkuvanovv commented
до изменений
  
  <img width="1241" alt="изображение" src="https://user-images.githubusercontent.com/39465918/111531691-ee11cf00-8775-11eb-8788-e5644f121c58.png">

2021-03-17 20:11 UTC, vladimirkuvanovv commented
после 

<img width="1200" alt="изображение" src="https://user-images.githubusercontent.com/39465918/111531851-1ac5e680-8776-11eb-91db-d45c43822107.png">

2021-03-18 15:57 UTC, fey requested changes
Также можно добавить ссылку на хероку, чтобы еще Андрей визуально посмотрел формочку

2021-03-18 15:57 UTC, fey commented on app/Http/Controllers/SolutionController.php
> +        $users = [];
Тут нужно прояснить, что за пользователи (авторы решений?)

2021-03-18 15:57 UTC, fey commented on app/Http/Controllers/SolutionController.php
> +            ->mapWithKeys(fn($solution) => [$solution->exercise->id => $solution->exercise->path . getExerciseTitle($solution->exercise)]);
А как в других местах сделана склейка пути и тайтла? 
Возможно это стоит вынести в метод, так как я встречаю такую структуру не впервые. 
Также я обычно рекомендую не пользоваться конкатенацией, символ точки в PHP для этого неудобен и незаметен.
Т.е. тут либо ввести метод для "Хелпера", либо отказаться от решения в одну строчку в пользу читаемости.

2021-03-18 15:57 UTC, fey commented on resources/lang/en/views.php
> +                'reset-btn' => 'Reset',
Предлагаю в ключах использовать snake_case для ениообразния, плюс можно не сокращать до `btn`

2021-03-18 15:57 UTC, fey commented on resources/views/solution/index.blade.php
> +                    {{ Form::select('filter[user_id]', $users, $filter['user_id'] ?? '', ['placeholder' => __('views.solution.index.table_header.author'), 'class' => 'form-control mr-2']) }}
user_id это int, а заменяешь строчкой? Думаю, что можно в контроллере просто мержить фильтры с дефолтными значениями, тогда здесь кода поменьше будет.

2021-03-24 07:05 UTC, amshkv reviewed
ну и мне бы посмотреть это в деле, все ли классы на месте, и нужные ли классы
вижу визуально что отступы между применить и сбросить и полями формы отличаются

2021-03-24 07:05 UTC, amshkv commented on resources/views/solution/index.blade.php
> +                <div>
если я правильно понимаю - то в финальном результате дополнительный `div` не нужен
да и `.d-flex` похоже тоже)

2021-03-24 07:05 UTC, amshkv commented on resources/views/solution/index.blade.php
> +                       class="remove-btn btn btn-outline-secondary ml-3"
что за remove-btn?
дефолтная ссылка разве не get?

2021-03-26 06:00 UTC, amshkv commented on resources/views/solution/index.blade.php
> +            <div class="mb-3 mt-3">
можно на `my-3` заменить

2021-03-30 08:41 UTC, vladimirkuvanovv commented
https://pure-springs-81425.herokuapp.com/

2021-03-30 08:49 UTC, merged